# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI
on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-13

    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 14.2

    - name: Build
      run: |
            set -o pipefail
            swift build
            
    - name: Run tests
      run: |
            set -o pipefail
            swift test
